apiVersion: v1
kind: Service
metadata:
  name: scraperr
  namespace: default
spec:
  type: NodePort
  selector:
    app: scraperr
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 32300
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: scraperr-api
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: scraperr-api
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
