apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nginx
  namespace: playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-nginx
  template:
    metadata:
      labels:
        app: hello-nginx
    spec:
      nodeSelector:
        node-role: worker
      containers:
        - name: nginx
          image: nginx:stable
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-nginx
  namespace: playground
spec:
  selector:
    app: hello-nginx
  ports:
    - port: 80
      targetPort: 80
