---
# helm dependency update argocd
# helm upgrade argocd argo/argo-cd --namespace argocd -f argocd/values.yaml
argo-cd:
  server:
    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: argocd.sloan.com
      tls: false
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: HTTP
        nginx.ingress.kubernetes.io/ssl-redirect: 'false'
  configs:
    params:
      server.insecure: 'true'
      timeout.reconciliation: 45s
