---
# Usage:
#   helm upgrade ingress-nginx ingress-nginx/ingress-nginx
#   -n ingress-nginx
#   -f /home-lab/cluster/ingress-nginx/values.yaml
controller:
  kind: Deployment
  nodeSelector:
    kubernetes.io/hostname: stormfather
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
  service:
    type: LoadBalancer
    externalTrafficPolicy: Local
    loadBalancerIP: 192.168.1.99
