---
# Usage:
#   helm upgrade ingress-nginx ingress-nginx/ingress-nginx
#   -n ingress-nginx
#   -f /home-lab/cluster/ingress-nginx/values.yaml
controller:
  kind: Service
  service:
    type: LoadBalancer
    externalTrafficPolicy: Local
    loadBalancerIP: 192.168.1.99
